// Verbal Reasoning: Critical Reasoning and Reading Comprehension.
// Same format as data-quant.js: { q, o: [correct, wrong×4], e }. The correct answer is listed first
// and the choices are shuffled on screen. Keep wrong answers about as long and specific as the right one.
// Reading Comprehension questions point to a passage in window.SETS with s: "<passage id>".
window.QB = window.QB || {};
window.SETS = window.SETS || {};

QB.cr = [
  { q: "Cafés in Milltown that installed free Wi-Fi last year saw their average daily sales rise by 15%, while sales at cafés without Wi-Fi did not change. Harbor Café, which has no Wi-Fi, should therefore install it to increase its sales.\n\nWhich of the following, if true, most seriously weakens the argument?",
    o: ["The cafés that installed Wi-Fi also extended their opening hours at the same time.",
        "Harbor Café's daily sales have been roughly steady for each of the past three years, in all seasons.",
        "Some customers of cafés with Wi-Fi stay for several hours at a time while buying only a single drink.",
        "Installing Wi-Fi would cost Harbor Café less than a month of its usual profit.",
        "Most Milltown cafés without Wi-Fi are located outside the town's center."],
    e: "The argument assumes Wi-Fi caused the sales rise. If those cafés also extended their hours at the same time, the longer hours could explain the rise, so Wi-Fi may not help Harbor Café. Location differences don't explain a change over time, and the cost of Wi-Fi doesn't affect whether it raises sales." },
  { q: "The city plans to reduce downtown traffic congestion by raising the fees at downtown parking garages. Since drivers will have to pay more to park, fewer of them will drive downtown, and congestion will ease.\n\nThe plan's success depends on which of the following assumptions?",
    o: ["A significant share of downtown traffic is made up of drivers who park in the downtown garages.",
        "Public transit routes into downtown are already being used at or near their full capacity each day.",
        "Most of the drivers who currently park downtown work for employers that reimburse them for parking.",
        "Parking in the suburbs costs less than parking in the downtown garages does.",
        "The extra revenue from the higher fees will be spent on downtown road repairs."],
    e: "Higher garage fees can only ease congestion if garage users are a meaningful part of the traffic. If most downtown traffic were through-traffic or deliveries, the plan would do little. Employer-paid parking would weaken the plan; the other options are irrelevant." },
  { q: "Researchers found that people who drink green tea daily have lower rates of heart disease than people who don't. They concluded that green tea helps protect against heart disease.\n\nWhich of the following, if true, most strengthens the researchers' conclusion?",
    o: ["The drinkers and non-drinkers had similar diets, exercise habits and smoking rates.",
        "Green tea contains less caffeine per cup than coffee or most black teas contain.",
        "Many of the people who drink green tea every day also take vitamin supplements on a regular basis.",
        "Rates of heart disease have fallen steadily across the whole country over the past decade or so.",
        "Some people who never drink green tea at all have no signs of heart disease."],
    e: "A correlation supports causation best when other explanations are ruled out. If the two groups had similar lifestyles, lifestyle can't explain the difference in heart disease, which strengthens the green-tea explanation. Vitamin use is an alternative cause (a weakener)." },
  { q: "To cut costs, Delmar Airlines plans to remove one flight attendant from each of its flights. Management argues that because passengers rarely ask flight attendants for help, the quality of service will not decline.\n\nWhich of the following, if true, casts the most doubt on management's argument?",
    o: ["Attendants spend most of their time on meals and safety checks, not on passenger requests.",
        "Delmar's main competitors have not reduced the number of flight attendants on their flights.",
        "Passengers who ask flight attendants for help usually do so on long flights rather than on short ones.",
        "Fuel, not staff pay, is the largest single operating cost for Delmar Airlines.",
        "Most Delmar passengers now book their tickets online rather than by phone."],
    e: "Management's reasoning assumes that answering requests is the main thing attendants do. If most of their work is meals and safety checks, fewer attendants could still hurt service, even though requests are rare." },
  { q: "Sales of printed encyclopedias have fallen by 90% over the last 20 years. Therefore, people today are less interested in reference information than they were 20 years ago.\n\nThe argument assumes which of the following?",
    o: ["People have not shifted to getting reference information from other sources, such as websites.",
        "Printed encyclopedias cost more today than they did 20 years ago, even after adjusting for inflation.",
        "Public libraries still buy new printed encyclopedias every few years for their collections.",
        "Reference information that is available to people today is more accurate than it was 20 years ago.",
        "Most encyclopedia publishers now sell their encyclopedias only in digital form."],
    e: "Falling sales of one source only show falling interest if people haven't simply switched to other sources. Negate it (people did switch to websites) and the argument falls apart, which is how you confirm a necessary assumption. Digital-only publishing is a reason to doubt the conclusion, not an assumption." },
  { q: "A new fertilizer, GrowMax, was applied to half of the fields on a large farm, and those fields produced 20% more wheat than the untreated fields. The farm manager concludes that GrowMax increases wheat yields.\n\nWhich of the following, if true, most strengthens the manager's conclusion?",
    o: ["The fields were randomly assigned to the two groups, and all received the same irrigation.",
        "GrowMax costs more per acre than the fertilizer that the farm had used in each of its previous seasons.",
        "Wheat prices rose sharply across the region during the growing season in which the test was carried out.",
        "Several of the treated fields had been planted with a newer, higher-yielding variety of wheat than the others.",
        "GrowMax was developed by one of the largest agricultural companies in the world."],
    e: "Random assignment and equal irrigation rule out the main alternative explanations (better fields or more water), so the yield gap is more likely due to GrowMax. The higher-yielding variety is an alternative cause and would weaken the conclusion." },
  { q: "Students who take music lessons score higher on math tests than students who don't. So schools should require all students to take music lessons in order to raise math scores.\n\nWhich of the following, if true, most weakens the argument?",
    o: ["Families that pay for music lessons also tend to pay for private math tutoring for their children.",
        "Some students who take music lessons score poorly on their math tests.",
        "Music lessons are currently offered at only half of the schools in the district.",
        "Math tests measure some of the same skills that are used in reading music.",
        "Requiring music lessons would increase the district's budget by about 2%."],
    e: "The argument jumps from correlation to causation. If music students also get math tutoring, the tutoring (or family resources) could explain the higher scores, so requiring music may not help. A few exceptions don't weaken a general correlation; shared skills would strengthen it." },
  { q: "The online retailer ShopFast will begin offering free shipping on all orders. Because free shipping will attract more customers, ShopFast's profits will increase.\n\nThe argument depends on which of the following assumptions?",
    o: ["The profit from the additional sales will exceed the added cost of paying for customers' shipping.",
        "None of ShopFast's main competitors currently offers free shipping on all of the orders it receives.",
        "Most of ShopFast's existing customers would keep shopping there even without free shipping.",
        "The cost of shipping packages is expected to fall over the course of the next year.",
        "Customers generally prefer the products ShopFast sells to the similar products sold by its competitors."],
    e: "More customers only means more profit if the extra sales outweigh the new shipping costs, which ShopFast now pays on every order. If the costs were larger, profit would fall. Competitors not offering free shipping might help, but the argument doesn't depend on it." },
  { q: "In Riverton, reported bicycle thefts fell by 30% in the year after the city installed security cameras at its bike racks. The police chief concluded that the cameras deterred bicycle theft.\n\nWhich of the following, if true, most seriously weakens the police chief's conclusion?",
    o: ["That year the city stopped taking theft reports online, and fewer people bothered to report thefts.",
        "Security cameras were also installed at the bike racks of several neighboring towns during that same year.",
        "Several bicycle thieves in Riverton were identified and arrested using the cameras' footage.",
        "Sales of new bicycles in Riverton increased during the year after the cameras went up.",
        "The cameras cost the city less to install than it had originally budgeted for them."],
    e: "The evidence is about reported thefts. If reporting became harder, reports could fall even if thefts didn't, so the drop may not reflect deterrence. Arrests using camera footage would support the chief." },
  { q: "To reduce employee turnover, a company plans to pay a bonus to every employee who stays with the company for three years.\n\nWhich of the following, if true, most strongly supports the prediction that the plan will reduce turnover?",
    o: ["In exit interviews, most departing employees named pay as the main reason for leaving.",
        "The company's rate of employee turnover is roughly the same as the rates at its main competitors.",
        "Hiring a new employee costs the company about a quarter of that employee's annual salary.",
        "Most employees who leave the company do so within their first six months of work.",
        "The company recently opened a second office in a city with lower living costs."],
    e: "If people leave mainly because of pay, a financial reward for staying addresses the cause, so the plan is likely to work. Hiring costs explain why the company wants lower turnover, not whether the plan achieves it. Early departures (within six months) suggest a 3-year bonus may not help." },
  { q: "Clara scored higher on a practice test after taking a test-prep course than she did on a practice test before the course. Therefore, the course improved her test-taking ability.\n\nThe conclusion depends on which of the following assumptions?",
    o: ["The practice test Clara took after the course was not easier than the one she took before it.",
        "Clara used no study materials other than the books and practice tests provided by the test-prep course.",
        "The test-prep course that Clara took is the most popular course of its kind available in her city.",
        "Clara will score even higher on the real test than she did on the practice tests.",
        "Other students in the same course also improved their practice-test scores afterward."],
    e: "If the second test were easier, the higher score could reflect the test, not an improvement in Clara. Using no other materials is too strong: the course could still have helped even if she used other materials too. Other students improving would strengthen but isn't required." },
  { q: "Because Lakeside's population is aging, demand for pediatricians (children's doctors) there will fall over the next decade. So the local hospital should reduce its pediatric staff.\n\nWhich of the following, if true, most weakens the argument?",
    o: ["A large housing development for young families is scheduled to open in Lakeside next year.",
        "Pediatricians earn less on average than doctors in most of the other medical specialties do.",
        "The hospital completed a renovation of its pediatric ward within the last two years.",
        "Older residents of Lakeside visit doctors more often than younger residents do.",
        "Several of the towns near Lakeside have also seen the average age of their residents rise in recent years."],
    e: "The prediction relies on the number of children falling. An influx of young families would increase the number of children and demand for pediatricians. How often older people see doctors is irrelevant to pediatric demand." },
  { q: "Mayor: Our town's new recycling program is sure to succeed, because a nearly identical program worked well in Westfield.\n\nWhich of the following, if true, most strengthens the mayor's argument?",
    o: ["Westfield and our town have similar populations, household habits and waste-collection systems.",
        "Westfield introduced its recycling program three years before our town introduced its own program.",
        "Our town's new recycling program will be paid for entirely with a grant from the state government.",
        "Some Westfield residents complained about the recycling program when it first started.",
        "Our town already runs a separate program for collecting and composting garden waste."],
    e: "An argument by analogy is only as strong as the similarity between the two cases. Showing that the towns are alike in the ways that matter for recycling makes Westfield's success a better guide to our town's." },
  { q: "The number of workplace injuries at Plant X rose from 20 last year to 30 this year. Clearly, the plant has become a more dangerous place to work.\n\nWhich of the following, if true, most weakens the argument?",
    o: ["Plant X doubled both its workforce and the total number of hours worked there this year.",
        "Most of this year's injuries at Plant X happened in its packing department.",
        "Injury counts at several of Plant X's competitors also rose this year.",
        "Plant X spent more on safety training this year than it did last year.",
        "Workers at Plant X are paid more than the average for the industry."],
    e: "Danger is about the injury rate, not the raw count. If hours worked doubled, 30 injuries is actually a lower rate than 20 was last year (15 per the old number of hours), so the plant may be safer." },
  { q: "Because the new drug Relivex lowered blood pressure in a clinical trial of 500 adults, doctors should prescribe it to all patients with high blood pressure.\n\nThe argument depends on which of the following assumptions?",
    o: ["Relivex does not have side effects that outweigh its benefits for many patients.",
        "Relivex costs less than every other blood-pressure medicine that is now available on the market.",
        "The clinical trial of Relivex included considerably more men than women among its 500 subjects.",
        "All patients who have been diagnosed with high blood pressure are more than 50 years old.",
        "Relivex lowered blood pressure more than any other drug that has been tested."],
    e: "Recommending it for all patients requires that its benefits aren't outweighed by harm for many of them. The argument doesn't need Relivex to be the cheapest or the best ever tested, only good enough to prescribe." },
  { q: "In a survey of our gym's members, 92% said they were satisfied with our facilities. So most people in the city would be satisfied with our facilities.\n\nWhich of the following, if true, most weakens the argument?",
    o: ["People who were unhappy with the facilities have mostly cancelled their memberships already.",
        "Our gym has more members than any other single gym or fitness club located anywhere in the city.",
        "Nearly every one of the gym's current members completed the satisfaction survey.",
        "The gym is planning to add a swimming pool, a sauna and several new group fitness classes next year.",
        "Satisfied members visit the gym more often than dissatisfied members do."],
    e: "The sample (current members) is self-selected: people who disliked the gym left, so the survey overstates satisfaction compared with the whole city. A high response rate makes the result accurate for members, not for everyone." },
  { q: "Birds of a certain species that live in cities sing at a higher pitch than birds of the same species that live in forests. Scientists hypothesize that the city birds sing higher so that they can be heard over low-pitched traffic noise.\n\nWhich of the following, if true, most supports the scientists' hypothesis?",
    o: ["In a city park, birds of this species sang at a lower pitch on weekends, when traffic was lighter.",
        "City birds of this species are, on average, slightly smaller than forest birds of the species.",
        "Forest birds of this species sing more often in the early morning than in the evening.",
        "Many different species of birds have adapted successfully to living in large cities.",
        "The overall level of low-pitched traffic noise in most cities has risen steadily over the last 50 years."],
    e: "If pitch drops when traffic drops, pitch tracks the noise, which directly supports the hypothesis. Smaller body size is an alternative explanation for higher pitch, so it would weaken." },
  { q: "To increase revenue, a museum plans to raise its admission fee from $10 to $15. Since attendance has been steady for years, the museum expects its admission revenue to rise by 50%.\n\nWhich of the following, if true, most seriously weakens the museum's expectation?",
    o: ["A free museum with similar exhibits recently opened a few blocks away.",
        "The museum's attendance is highest during the summer tourist season.",
        "The museum's operating costs have risen by about 10% over the past year.",
        "Most of the museum's visitors are tourists who visit the museum only once.",
        "Other museums in the city charge admission fees of between $12 and $20."],
    e: "A 50% revenue rise requires attendance to hold steady at the higher price. A nearby free alternative makes it likely many visitors will go elsewhere. Rising costs affect profit, not admission revenue." },
  { q: "A new highway bypass will route through traffic around the town of Oakville instead of along its Main Street. So the shops on Main Street will lose a significant amount of business.\n\nThe argument depends on which of the following assumptions?",
    o: ["A large share of Main Street's customers are travelers passing through Oakville.",
        "Shops on Main Street tend to charge higher prices than shops elsewhere in the region do.",
        "The bypass will make Main Street quieter and more pleasant for local shoppers.",
        "Oakville residents rarely travel to other towns to do their shopping, even for larger purchases.",
        "Construction of the new highway bypass will take about two years to finish."],
    e: "Rerouting through traffic only hurts the shops if through travelers are an important source of their customers. If nearly all customers were locals, the bypass wouldn't matter much. A quieter street would, if anything, help." },
  { q: "After Brightline Software switched its staff to a four-day workweek, output per employee rose by 12%. The CEO concluded that the shorter week caused the increase.\n\nWhich of the following, if true, most strengthens the CEO's conclusion?",
    o: ["Brightline made no other changes to its staff, tools or projects during the period.",
        "Brightline's main competitors kept their employees on a five-day workweek.",
        "Brightline's employees said in a survey that they liked the four-day week.",
        "Brightline plans to keep the four-day workweek in place for next year.",
        "Brightline hired several experienced senior engineers in the weeks just before making the switch."],
    e: "Ruling out other changes removes alternative explanations for the productivity rise, making the shorter week the likeliest cause. Hiring senior engineers would be an alternative cause (a weakener)." },
  { q: "A study of 1,000 professional chess players found that their memory scores were well above average. So playing chess improves memory.\n\nWhich of the following, if true, most weakens the conclusion?",
    o: ["People with strong memories are more likely to succeed at chess and become professionals.",
        "Most professional chess players started playing the game regularly when they were young children.",
        "A few of the professional chess players in the study had below-average memory scores.",
        "The study also measured the reaction times and the eyesight of the professional chess players in it.",
        "Chess is played regularly by millions of amateur players around the world."],
    e: "This is reverse causation: strong memory may lead to chess success rather than chess improving memory. A few exceptions don't undermine an average." },
  { q: "Nutritionist: Brand Z cereal contains 30% less sugar per serving than Brand Y. So children who switch from Brand Y to Brand Z will consume less sugar each day.\n\nThe nutritionist's conclusion depends on which of the following assumptions?",
    o: ["Children who switch won't eat bigger portions or add sugar to make up the difference.",
        "Brand Z costs about the same per box as Brand Y does at most grocery stores.",
        "Most children prefer the taste of Brand Y cereal to the taste of Brand Z.",
        "Brand Z contains more fiber and more vitamins per serving than Brand Y.",
        "Sugar is the leading cause of tooth decay among children of elementary and high school age."],
    e: "Less sugar per serving only means less sugar per day if children don't compensate with bigger portions, added sugar or other sweet foods. Price and fiber are irrelevant to the sugar conclusion." }
];

QB.cr2 = [
  { q: "Last year Hilltop Hospital hired 20 more nurses, yet the average time patients waited to see a nurse increased.\n\nWhich of the following, if true, best explains this?",
    o: ["The number of patients treated at Hilltop more than doubled after a nearby hospital closed.",
        "Nurses at Hilltop Hospital earn more than the nurses at most other hospitals in the region.",
        "Hilltop's nurses spend part of every shift completing paperwork and updating patient records.",
        "Most of the nurses Hilltop hired last year had several years of experience.",
        "Patients at Hilltop give their nurses high ratings in satisfaction surveys."],
    e: "To resolve a paradox, find a fact that makes both parts true. If patient numbers more than doubled, demand grew faster than the nursing staff, so waits could rise despite the new hires. Paperwork that has always existed doesn't explain a change." },
  { q: "Although the average fare on the Denton–Carver air route fell by 20% this year, the airline's total revenue from the route rose.\n\nWhich of the following, if true, best explains this?",
    o: ["The number of passengers flying the route rose by 40% this year.",
        "Fuel costs for flights on the route rose sharply this year.",
        "The airline also cut its fares on several of its other domestic routes.",
        "Last year, many of the flights on the route were half empty.",
        "Most passengers on the route are traveling on business trips."],
    e: "Revenue = fare × passengers. With fares at 0.8× and passengers at 1.4×, revenue is 1.12× last year's, a rise. Half-empty flights last year show there was room to grow but don't show that growth happened." },
  { q: "In a certain country, every licensed pharmacist has a university degree in pharmacy. Some people with a university degree in pharmacy work as researchers rather than as pharmacists. No one who is not a licensed pharmacist may legally dispense prescription drugs.\n\nIf the statements above are true, which of the following must also be true?",
    o: ["Everyone who legally dispenses prescription drugs in the country has a degree in pharmacy.",
        "Everyone in the country who holds a university degree in pharmacy is also a licensed pharmacist.",
        "Some of the researchers who have pharmacy degrees also legally dispense prescription drugs.",
        "Most people who earn a degree in pharmacy go on to become licensed pharmacists.",
        "Some licensed pharmacists in the country also work as pharmacy researchers."],
    e: "Chain the rules: legally dispensing → licensed pharmacist → pharmacy degree. So anyone who legally dispenses has a degree. The reverse (degree → pharmacist) doesn't follow, and nothing tells us about \"most\" or about pharmacists doing research." },
  { q: "Many economists predicted that a new tax on sugary drinks would reduce consumption. **Sales of sugary drinks in the city did fall by 15% in the first year.** However, this drop may not reflect lower consumption, since **many shoppers near the city's border began buying their drinks in neighboring towns, where the tax does not apply.**\n\nIn the argument above, the two portions in boldface play which of the following roles?",
    o: ["The first is evidence that seems to support a prediction; the second gives a reason to doubt that the evidence shows what it seems to.",
        "The first is the main conclusion of the argument; the second is evidence that the argument offers directly in support of that conclusion.",
        "The first is evidence against the economists' prediction; the second is further evidence that supports the economists' prediction.",
        "The first is a prediction that the argument rejects; the second is the main conclusion that the argument draws about that prediction.",
        "The first is a finding that the argument accepts as proof of the prediction; the second is a consequence of that same finding."],
    e: "The 15% drop appears to confirm the prediction (it's evidence, not a conclusion). The second portion explains the drop another way (cross-border buying), which undercuts the evidence. The argument's actual conclusion is that the drop \"may not reflect lower consumption\"." },
  { q: "A city plans to install Wi-Fi on all of its buses in order to increase the number of people who ride the bus.\n\nWhich of the following would be most useful to know in evaluating whether the plan is likely to achieve its goal?",
    o: ["Whether a lack of Wi-Fi is among the reasons people who could take the bus choose not to",
        "Whether the Wi-Fi equipment installed on the buses will need to be replaced within five years",
        "How many of the city's current bus drivers are in favor of installing Wi-Fi on all of the buses",
        "Whether other cities of similar size have more bus routes than this city has",
        "How much current riders pay for a monthly pass on the city's bus system"],
    e: "Evaluate questions ask for information whose answer would make the plan look better or worse. If non-riders avoid the bus partly for lack of Wi-Fi, the plan could work; if Wi-Fi plays no role in their choice, it won't. Equipment life affects cost, not ridership." },
  { q: "Every employee at Dorland Inc. who completed the leadership course was promoted within a year. Dana, a Dorland employee, was promoted within a year, so Dana must have completed the leadership course.\n\nWhich of the following describes a flaw in the reasoning above?",
    o: ["It treats something that guarantees a promotion as if it were the only possible way to get promoted.",
        "It relies on a sample of employees that is too small to be representative of all workers.",
        "It assumes without any justification that the leadership course was what caused the promotions.",
        "It confuses the total number of promotions with the rate at which promotions occur.",
        "It draws a conclusion about every employee from information about a single employee."],
    e: "\"Course → promoted\" doesn't mean \"promoted → course\". Dana could have been promoted for other reasons. This is the classic sufficient/necessary (converse) error." },
  { q: "In 2023, Company A sold more laptops than Company B did. However, Company B's total revenue from laptop sales was higher than Company A's.\n\nIf the statements above are true, which of the following must also be true?",
    o: ["In 2023, Company B's average revenue for each laptop it sold was higher than Company A's average.",
        "In 2023, Company B's laptops were of higher quality than Company A's laptops.",
        "In 2023, Company B earned a larger profit from its laptops than Company A did.",
        "In 2023, Company A sold at least some of its laptops for less than they cost to make.",
        "In 2023, Company B charged more than Company A for laptops in every price range."],
    e: "Revenue = number sold × average price. B sold fewer but earned more, so B's average revenue per laptop must be higher. Profit depends on costs, which aren't given, and \"every price range\" is far too strong." },
  { q: "Studies show that people who use sunscreen regularly have a higher rate of skin cancer than people who rarely use it. Yet dermatologists agree that sunscreen protects against skin cancer.\n\nWhich of the following, if true, most helps to resolve the apparent discrepancy?",
    o: ["Regular sunscreen users spend far more time in strong, direct sunlight than people who rarely use it.",
        "Some brands of sunscreen protect against more types of harmful sunlight than other brands do.",
        "Rates of skin cancer have been rising steadily in many countries for several decades.",
        "Most people apply much less sunscreen than the amount that is recommended on the product's label.",
        "Dermatologists recommend that people of all ages use sunscreen when they go outdoors."],
    e: "If regular users are exactly the people with the most sun exposure, they can have more skin cancer overall even though sunscreen lowers their risk compared with the same exposure unprotected. Under-application explains weaker protection, not a higher rate than non-users." },
  { q: "The town's new bike lanes were completed in May. Cycling accidents from June through August fell by 25% compared with the same months last year, so the town council concluded that the lanes made cycling safer.\n\nWhich of the following would be most useful to determine in order to evaluate the council's conclusion?",
    o: ["Whether about as many people cycled from June through August this year as last year",
        "Whether the construction of the bike lanes was completed on time and within its budget",
        "Whether cycling accidents in the town are generally more common in summer than in winter",
        "Whether most of the cyclists in the town wear helmets whenever they ride",
        "Whether neighboring towns are planning to build bike lanes of their own"],
    e: "Fewer accidents only shows safer cycling if the amount of cycling didn't fall too. If far fewer people cycled this summer, accidents could drop without the lanes having any effect. Summer vs. winter doesn't matter because the same months are compared." },
  { q: "**Some analysts argue that Rennick Corp. should close its unprofitable retail stores.** It's true that the stores lose money on their own. But customers who visit a Rennick store are three times as likely as other customers to buy Rennick products online. **Closing the stores would therefore probably reduce the company's overall profit.**\n\nIn the argument above, the two portions in boldface play which of the following roles?",
    o: ["The first is a position that the argument opposes; the second is the main conclusion that the argument draws.",
        "The first is a position that the argument opposes; the second is evidence offered against that position.",
        "The first is the main conclusion of the argument; the second is a consideration that supports it.",
        "The first is a position that the argument supports; the second is an objection raised against it.",
        "The first is evidence the argument relies on; the second is a prediction the argument rejects."],
    e: "The argument disagrees with the analysts (first portion). The word \"therefore\" signals that the second portion is the argument's conclusion; the evidence for it is the online-buying statistic in the middle." },
  { q: "Every tree species in Greenvale Forest that sheds its leaves in winter is a hardwood. None of the hardwood species in Greenvale Forest grows taller than 30 meters. The redcap pine, which grows in Greenvale Forest, often reaches 40 meters.\n\nIf the statements above are true, which of the following must be true?",
    o: ["The redcap pine does not shed its leaves in winter.",
        "The redcap pine is the tallest tree in Greenvale Forest.",
        "Every Greenvale tree over 30 meters tall is a pine.",
        "Some hardwood species in Greenvale Forest are evergreen.",
        "Most Greenvale trees that shed their leaves are under 20 meters."],
    e: "Redcap pines exceed 30 meters, so they aren't hardwoods. Every species that sheds its leaves is a hardwood, so a non-hardwood can't shed its leaves in winter. Nothing supports the other claims." },
  { q: "Game designer: Critics say our new video game is too violent. But several of those critics have designed games with violent scenes themselves. So their criticism is unfounded.\n\nThe designer's reasoning is flawed because it:",
    o: ["rejects a criticism because of the critics' own conduct instead of addressing it",
        "assumes that what is true of one video game must also be true of every other video game",
        "mistakes a condition that is necessary for a game's success for one that is sufficient",
        "relies on the opinions of a group of players that may not be representative of all players",
        "treats the fact that two things happened together as proof that one of them caused the other"],
    e: "Whether the critics are hypocrites has no bearing on whether the game is too violent. Attacking the source instead of the claim is an ad hominem flaw." },
  { q: "Over the past decade, the number of people in Norland who own electric cars has risen sharply. Yet total gasoline sales in Norland have also risen over the same period.\n\nWhich of the following, if true, best explains this?",
    o: ["Norland's population and number of cars on the road have grown quickly over the decade.",
        "Electric cars cost more to buy than gasoline-powered cars of a similar size and quality.",
        "Many of Norland's electric-car owners charge their cars overnight at their own homes.",
        "The price of gasoline in Norland has risen by more than the rate of inflation over the decade.",
        "Norland's government has offered tax credits to people who buy new electric cars."],
    e: "If the total number of cars grew quickly, the number of gasoline cars could rise even as electric cars became more common, so gasoline sales could rise too. Higher gasoline prices would, if anything, reduce sales." },
  { q: "A school district is replacing printed textbooks with tablets in order to reduce costs.\n\nWhich of the following would be most important to know in evaluating whether the change will reduce costs?",
    o: ["How the full cost of buying, repairing and replacing tablets compares with the cost of printed books",
        "Whether students in the district would rather read their assigned material on tablets than in printed textbooks",
        "Whether any of the neighboring school districts have already replaced their printed textbooks with tablets",
        "How many of the district's teachers have used tablets in their own classrooms before this school year",
        "Whether the tablets that the district plans to buy can connect to the internet from students' homes"],
    e: "The goal is cost savings, so the key comparison is the full cost of tablets (including repairs and replacements) versus books. Student preferences and other districts' choices don't answer the cost question." },
  { q: "At Kline College, the percentage of students majoring in economics rose from 8% in 2020 to 10% in 2024, while the total number of students at the college fell. (Each student has exactly one major.)\n\nIf the statements above are true, which of the following must also be true?",
    o: ["The share of Kline students majoring in something other than economics fell.",
        "The number of Kline students majoring in economics rose between 2020 and 2024.",
        "The number of Kline students majoring in economics fell between 2020 and 2024.",
        "By 2024, economics had become the most popular major at Kline College.",
        "Between 2020 and 2024, more students switched into economics than out of it."],
    e: "With one major each, the non-economics share is 100% minus the economics share: 92% in 2020 and 90% in 2024, so it fell. The number of economics majors could have gone either way, because the total fell while the share rose." },
  { q: "Environmentalist: Supporters say the proposed dam will provide cheap electricity. But the same was said of the Arvin Dam, whose final cost was triple the original estimate. So we should doubt the cost estimates for the proposed dam.\n\nThe environmentalist's argument proceeds by:",
    o: ["drawing a conclusion about a proposal from what happened in a similar earlier case",
        "showing that some of the supporters of the proposal have a financial conflict of interest",
        "questioning whether producing cheap electricity is a goal worth pursuing in the first place",
        "proposing a different and less costly method of producing the same electricity",
        "pointing out that the supporters' claims about the proposal contradict each other"],
    e: "The argument uses the Arvin Dam as an analogy: because a similar project's estimate proved wrong, this one's may too. It doesn't attack the supporters' motives or offer an alternative." },
  { q: "Although Westbury's crime rate has fallen for five years in a row, the percentage of Westbury residents who say they feel unsafe has risen over the same period.\n\nWhich of the following, if true, best explains this?",
    o: ["Local news coverage of crime in Westbury has greatly increased over those five years.",
        "Westbury's police department has hired more officers during each of the last five years.",
        "Crime rates in the cities near Westbury have also fallen during the last five years.",
        "Most of the crimes committed in Westbury are property crimes rather than violent crimes.",
        "Westbury residents who feel unsafe are more likely than others to install home alarms."],
    e: "Feeling unsafe depends on perception. Much more crime coverage could make residents perceive more danger even while actual crime falls. A fact that has always been true (mostly property crime) can't explain a change." },
  { q: "A doctor claims that eating an apple a day reduces the number of colds a person gets. Her evidence is that her patients who eat an apple daily report fewer colds than her other patients.\n\nWhich of the following would be most useful to know in evaluating the doctor's claim?",
    o: ["Whether the apple eaters differ from the others in other health habits, such as sleep and exercise",
        "Whether apples contain more vitamins and minerals per serving than oranges and other common fruits do",
        "How many colds the average adult gets in a typical year, compared with the number the average child gets",
        "Whether fresh apples are available in local stores during every season of the year",
        "Which varieties of apples the doctor's patients who eat an apple each day tend to prefer"],
    e: "If apple eaters also sleep and exercise more, those habits could explain the fewer colds. If the groups are otherwise alike, the apple explanation gains support. That's what makes this information useful either way." },
  { q: "Most of the rare-earth metals used in electronics are mined in only a few countries. Recycling old electronics can recover these metals, but today only about 1% are recovered this way, mainly because collecting and processing old devices costs more than mining new metal.\n\nThe statements above most strongly support which of the following?",
    o: ["If newly mined rare-earth metals became much more expensive, recycling them would likely increase.",
        "Rare-earth metals are not used in any products other than consumer electronics such as phones.",
        "Recycling old electronics will soon replace mining as the main source of rare-earth metals.",
        "The few countries that mine rare-earth metals will soon begin to restrict their exports.",
        "Most old electronic devices are thrown away because they cannot be repaired economically."],
    e: "Recycling is rare mainly because it costs more than mining. If mined metal got much more expensive, that cost gap would shrink, so recycling would likely increase. The other options go beyond what the passage says." },
  { q: "Car thefts in Eastvale rose by 50% last year, while car thefts in Westvale rose by only 10%. So last year more cars were stolen in Eastvale than in Westvale.\n\nThe reasoning above is flawed because it:",
    o: ["compares numbers of thefts using only percent changes, without the starting numbers",
        "assumes that car thefts will continue to rise at the same pace in both towns in the coming years",
        "relies on police reports of car thefts that may be incomplete or inaccurate in both of the towns",
        "treats a correlation between two trends as proof that one caused the other",
        "ignores the possibility that some of the stolen cars were later recovered"],
    e: "A 50% rise from 20 thefts (to 30) is far fewer than a 10% rise from 1,000 (to 1,100). Percent changes say nothing about actual numbers unless you know the bases." }
];

// ---------- Reading Comprehension ----------
SETS["rc-fungi"] = { title: "Passage", text: [
  "Beneath most forests lies a web of fungal threads, called mycorrhizal networks, that link the roots of neighboring trees. The fungi supply trees with water and minerals in exchange for sugars produced by photosynthesis. In the 1990s, experiments using radioactive carbon showed that carbon could pass from one seedling to another through these shared fungi, and the finding soon grew into a popular picture: forests as cooperative communities in which large \"mother trees\" feed their shaded offspring and warn neighbors of insect attacks.",
  "In recent years, however, a number of forest ecologists have argued that this picture has outrun the evidence. They point out that most of the key experiments were carried out on seedlings in greenhouses or small plots, not on mature trees in intact forests. Moreover, the amounts of carbon transferred were usually small, and in many studies it was unclear whether the carbon moved through the fungi at all or through the soil, or whether it ever reached the leaves of the receiving plant rather than remaining in the fungus itself.",
  "None of this means that the networks are unimportant. The critics readily accept that mycorrhizal fungi are vital to tree health and that some resources move between plants. Their concern is with the claim that trees use the networks deliberately to help one another, which, they argue, is best treated as a hypothesis awaiting field tests rather than as an established fact. Some of them also worry that popular accounts, by presenting the hypothesis as settled, could lead forest managers to base decisions on it before it has been properly tested."
]};
QB.rc = [
  { s: "rc-fungi", q: "The primary purpose of the passage is to",
    o: ["describe a popular view of mycorrhizal networks and explain why some scientists doubt it",
        "argue that mycorrhizal networks play little or no role in keeping the trees of a forest healthy",
        "explain the methods ecologists used in the 1990s to trace carbon moving between tree seedlings",
        "compare how trees grow in greenhouses with how they grow in mature, intact forests",
        "propose new field experiments that could settle the debate about how trees share resources"],
    e: "Paragraph 1 presents the \"cooperative forest\" picture; paragraphs 2–3 explain why critics think it has \"outrun the evidence\". The passage explicitly says the networks are important, so the second option contradicts it." },
  { s: "rc-fungi", q: "According to the passage, the critics accept which of the following?",
    o: ["Mycorrhizal fungi are vital to tree health, and some resources pass between plants.",
        "Large trees deliberately use fungal networks to feed their shaded offspring.",
        "Carbon rarely moves through the soil itself between the roots of neighboring trees in a forest.",
        "Greenhouse studies on young seedlings are more reliable than studies carried out in the field.",
        "Trees warn their neighbors of insect attacks by sending signals through fungi."],
    e: "Paragraph 3: \"The critics readily accept that mycorrhizal fungi are vital to tree health and that some resources move between plants.\" Deliberate helping is exactly what they doubt." },
  { s: "rc-fungi", q: "The author mentions that the carbon may have remained \"in the fungus itself\" most likely in order to",
    o: ["suggest that a transfer of carbon doesn't necessarily show that one plant fed another",
        "show that the fungi use more carbon than the trees that they are attached to in the forest",
        "explain why experiments using radioactive carbon are no longer carried out",
        "argue that fungi, not trees, are the most important organisms in a forest",
        "support the claim that greenhouse studies measure the movement of carbon more accurately than field studies"],
    e: "If the carbon stayed in the fungus, it never reached the \"receiving\" plant, so the experiment wouldn't show that one tree nourished another. It's one of the critics' reasons for doubting the popular picture." },
  { s: "rc-fungi", q: "It can be inferred from the passage that the critics would most likely agree with which of the following statements?",
    o: ["Claims that trees cooperate deliberately should be tested on mature trees in natural forests.",
        "Forest managers should remove fungal networks to encourage trees to grow faster.",
        "The experiments of the 1990s were deliberately designed to mislead other scientists in the field.",
        "Popular accounts of forests have generally understated how much trees share resources with one another.",
        "Mycorrhizal networks exist only between seedlings, never between mature trees."],
    e: "The critics call deliberate cooperation a \"hypothesis awaiting field tests\" and fault studies done on seedlings in greenhouses, so they'd want tests on mature trees in intact forests. They think popular accounts overstate, not understate, the evidence." }
];

SETS["rc-platforms"] = { title: "Passage", text: [
  "Many of the most valuable companies of recent decades are platforms: businesses that connect two groups of customers, such as buyers and sellers, drivers and riders, or readers and advertisers. Because each group values the platform more when the other group is larger, platforms face a pricing problem that ordinary firms don't. A platform that charges both sides the full cost of serving them may never attract enough of either side to become useful.",
  "The usual solution is to subsidize one side, charging it little or nothing, and to earn money from the other. Which side is subsidized depends less on which side is poorer than on which side is more sensitive to price and more valuable to the other side. Video-game console makers, for example, have often sold consoles at or below cost while charging game publishers fees on every game sold, because a large base of console owners is what persuades publishers to make games at all. Similarly, a newspaper may keep its cover price low because its readers, not its advertisers, are the scarcer side.",
  "This strategy carries risks. A platform that subsidizes one side heavily may find it hard to raise prices later, because customers come to expect low prices and rivals can lure them away. And if the paying side can reach the subsidized side in some other way, it may stop paying. For these reasons, economists who study platforms argue that low prices on one side should not be mistaken for generosity, nor necessarily for predatory pricing: they are often simply the price of getting both sides on board."
]};
QB.rc.push(
  { s: "rc-platforms", q: "The passage is primarily concerned with",
    o: ["explaining why platforms often charge one group of customers much less than the other group",
        "arguing that platforms should be regulated to prevent them from harming competitors",
        "describing how video-game console makers became highly profitable over recent decades",
        "comparing the business models of newspapers with those of online ride-sharing services",
        "showing that platforms usually subsidize whichever group of customers is poorer"],
    e: "The passage explains the two-sided pricing problem, how platforms solve it by subsidizing one side, and the risks of doing so. Consoles and newspapers are just examples." },
  { s: "rc-platforms", q: "According to the passage, which side of a platform is usually subsidized?",
    o: ["The side that is more sensitive to price and more valuable to the other side",
        "The side that has less money available to spend on the platform's various services",
        "The side that was the first to start using the platform",
        "The side whose members tend to remain more loyal to the platform over a long period of time",
        "The side that costs the platform more to serve each month"],
    e: "Paragraph 2: which side is subsidized \"depends less on which side is poorer than on which side is more sensitive to price and more valuable to the other side.\"" },
  { s: "rc-platforms", q: "The example of the newspaper in the second paragraph suggests that, for that newspaper,",
    o: ["attracting readers is harder than attracting advertisers",
        "advertisers are more sensitive to price than readers are",
        "the cover price is its main source of revenue",
        "its readers value the advertisements more than they value the articles",
        "it has more readers than any of its competitors"],
    e: "The newspaper keeps the cover price low \"because its readers, not its advertisers, are the scarcer side\", so readers are the harder side to attract and are subsidized." },
  { s: "rc-platforms", q: "Which of the following, if true, would best illustrate one of the risks described in the third paragraph?",
    o: ["Game publishers start selling games directly to console owners, avoiding the console maker's fees.",
        "A console maker lowers the price of its console and sells more consoles than it did in any year before.",
        "A newspaper raises its advertising rates and its advertising revenue grows by 10% over the following year.",
        "A ride-sharing service offers new riders a discount and attracts more drivers to its platform as a result.",
        "An online marketplace charges sellers a small fee and buyers nothing, and both groups keep growing."],
    e: "The third paragraph warns that \"if the paying side can reach the subsidized side in some other way, it may stop paying.\" Publishers selling directly to console owners is exactly that. The other options describe the strategy working." }
);

SETS["rc-microfinance"] = { title: "Passage", text: [
  "When microfinance, the practice of making very small loans to poor entrepreneurs, spread across the developing world in the 1990s and 2000s, it was widely celebrated as a powerful tool against poverty. Stories of borrowers who used a small loan to buy a sewing machine or a cow and then built a thriving business were common, and supporters predicted that access to credit would lift millions of households out of poverty.",
  "Beginning around 2009, however, a series of randomized studies tested these claims by comparing areas where lenders opened branches with similar areas where they did not. The results were more modest than the stories suggested. In most studies, access to microloans led some households to start or expand businesses, but average household income and consumption did not rise significantly, and measures such as children's school attendance and women's decision-making power changed little.",
  "Some researchers concluded that microfinance had been oversold. Others offered a more nuanced reading. The averages, they noted, concealed wide differences: a minority of borrowers who already ran businesses saw large gains, while many others used loans mainly to smooth their spending, for example by paying for a medical emergency without selling a farm animal. On this view, microfinance works less as a ladder out of poverty than as a financial tool that makes poor households' lives somewhat more manageable, a real but less dramatic benefit."
]};
QB.rc.push(
  { s: "rc-microfinance", q: "The passage is primarily concerned with",
    o: ["contrasting early hopes for microfinance with later evidence and interpretations of its effects",
        "explaining how randomized studies are designed and why they are more accurate than surveys",
        "arguing that microfinance lenders should stop making loans to households that don't already run businesses",
        "describing the history of lending to poor households around the world from ancient times to the present",
        "showing that microfinance has increased children's school attendance in developing countries"],
    e: "Paragraph 1 gives the early optimism, paragraph 2 the more modest evidence, and paragraph 3 two ways of interpreting it. The passage says school attendance \"changed little\"." },
  { s: "rc-microfinance", q: "According to the passage, the randomized studies found that access to microloans",
    o: ["led some households to start or expand businesses but did not significantly raise average income",
        "significantly raised both average household income and average household consumption over time",
        "caused most borrowers to sell their farm animals or other assets in order to repay their loans on time",
        "had no measurable effect at all on whether households started new businesses or expanded existing ones",
        "greatly increased women's power to make decisions within their households"],
    e: "Paragraph 2: \"access to microloans led some households to start or expand businesses, but average household income and consumption did not rise significantly.\"" },
  { s: "rc-microfinance", q: "The example of paying for a medical emergency without selling a farm animal is used to illustrate",
    o: ["a way in which loans can benefit a household without increasing its income",
        "the reason that most microfinance borrowers fail to repay their loans on time",
        "a type of business that borrowers commonly start after receiving a microloan",
        "a flaw in the design of the randomized studies of microfinance's effects",
        "the kind of story that supporters of microfinance told in the 1990s and 2000s"],
    e: "It's an example of using loans \"to smooth their spending\": handling a shock without selling an asset. That helps a household cope without raising its average income." },
  { s: "rc-microfinance", q: "The researchers who offered \"a more nuanced reading\" would most likely agree with which of the following?",
    o: ["Looking only at average results can hide the fact that some borrowers benefit a great deal.",
        "Microfinance has done more harm than good to most of the households that used it.",
        "The randomized studies greatly overstated the benefits that microfinance brings to its borrowers.",
        "Stories about successful borrowers accurately describe what usually happens to typical borrowers.",
        "Poor households have no real need for financial tools such as loans or savings accounts."],
    e: "They \"noted\" that \"the averages concealed wide differences\", with a minority of existing business owners seeing \"large gains\". They see a real benefit, so they wouldn't say it did more harm than good." }
);

SETS["rc-photography"] = { title: "Passage", text: [
  "A familiar account of nineteenth-century art holds that the invention of photography freed painting from the task of recording the visible world. Once a camera could capture a likeness more cheaply and precisely than any portrait painter, the story goes, painters turned to what the camera could not do (expressing emotion, exploring color, breaking forms apart) and so paved the way for modern art.",
  "Art historians have increasingly questioned this account. For one thing, early photographs were far from the perfect mirrors the story assumes: exposures were long, colors were absent, and moving subjects blurred. For decades, many painters regarded photography less as a rival than as a tool, using photographs as studies for compositions, much as earlier painters had used drawings. Some of the painters most closely associated with breaking from realism were also enthusiastic users of the camera.",
  "Moreover, the movement away from strict realism had roots that predate photography, in Romantic painters' interest in mood and imagination. None of this means photography had no effect. It clearly transformed the market for portraits, driving many miniature painters out of business. But the relationship between the two arts was one of exchange rather than simple replacement, and the story of painting being \"freed\" by the camera flatters the idea of a clean break that the historical record does not support."
]};
QB.rc.push(
  { s: "rc-photography", q: "The author's main purpose in the passage is to",
    o: ["challenge a common explanation of how the invention of photography influenced painting",
        "argue that photography had no effect at all on nineteenth-century painting",
        "describe the technical limits of the earliest photographic equipment",
        "explain why miniature portrait painters went out of business",
        "defend the view that photography is an art form equal to painting"],
    e: "The author presents the familiar \"freed painting\" account and then gives reasons to doubt it. The author explicitly says photography did have effects, so \"no effect at all\" is wrong." },
  { s: "rc-photography", q: "The author mentions long exposures, the absence of color and blurred subjects in order to",
    o: ["show that early photographs could not simply replace paintings as records of the visible world",
        "explain why most painters in the nineteenth century refused to use photographs in their own work",
        "argue that early photography was not considered a real art form in the eyes of most critics of the time",
        "describe the improvements that later photographers made to cameras and film",
        "support the claim that portrait painters were driven out of business by photography"],
    e: "These limits undercut the assumption that early photographs were \"perfect mirrors\" that made realistic painting unnecessary." },
  { s: "rc-photography", q: "The passage suggests that the author would most likely agree that",
    o: ["painters and photographers influenced each other in the nineteenth century",
        "modern art would not have developed if photography had never been invented",
        "Romantic painters were the first artists to use photographs as studies for their paintings",
        "photography had no effect on the market for painted portraits",
        "painters who used photographs were more realistic than those who didn't"],
    e: "The author says the relationship was \"one of exchange rather than simple replacement\". The author says photography transformed the portrait market, and traces non-realism to pre-photographic roots." },
  { s: "rc-photography", q: "Which of the following, if true, would most weaken the author's argument?",
    o: ["Letters show that most leading painters of the time abandoned realism because they couldn't compete with the camera.",
        "Some nineteenth-century painters kept large collections of photographs that they used as studies for their own paintings.",
        "The number of miniature portrait painters fell sharply in the decades after photography was first introduced in 1839.",
        "Several Romantic painters wrote about the importance of mood and imagination in painting before 1839.",
        "Early photographs of busy street scenes often showed moving people as faint blurs."],
    e: "The author argues against the idea that painters turned from realism because of the camera. Direct evidence that painters did exactly that would weaken the argument. The other options support the author's points." }
);

SETS["rc-wages"] = { title: "Passage", text: [
  "In the standard textbook model of a labor market, many employers compete for workers, and each employer must pay the going wage or lose its staff. In such a market, a legal minimum wage set above the going wage makes labor more expensive, and employers respond by hiring fewer workers. For decades this prediction, that minimum wages reduce employment, was treated by many economists as close to settled.",
  "An alternative model, known as monopsony, begins from a different assumption: that employers have some power to set wages because workers cannot easily switch jobs. Workers may face long commutes to other employers, lack information about openings, or have skills valued by only a few firms. An employer with such power can pay less than a worker's contribution to its revenue and still keep most of its staff. In this situation, a moderate minimum wage can actually raise employment: because the employer must now pay the higher wage anyway, it no longer gains by holding wages down, and it may hire workers it previously turned away.",
  "Which model better describes real labor markets is an empirical question, and studies of minimum-wage increases have produced mixed results. Many find small or no employment losses from moderate increases, a result that is hard to reconcile with the textbook model but consistent with monopsony. Few economists, however, believe that monopsony power is unlimited; most agree that a minimum wage set high enough would reduce employment even where employers have some wage-setting power."
]};
QB.rc.push(
  { s: "rc-wages", q: "The passage is primarily concerned with",
    o: ["presenting two models that make different predictions about the effects of a minimum wage",
        "arguing that governments should raise their minimum wages to much higher levels than they are today",
        "describing how economists measure employment in labor markets that have only a few large employers",
        "explaining why workers often find it difficult to switch from one job to another",
        "showing that the textbook model of labor markets has been proven entirely wrong"],
    e: "The passage sets out the textbook model, then the monopsony model, then how evidence bears on them. It doesn't advocate a policy, and it says the question is still empirical." },
  { s: "rc-wages", q: "According to the monopsony model described in the passage, a moderate minimum wage can raise employment because",
    o: ["the employer no longer gains by holding wages down, so it may hire workers it turned away",
        "workers become more productive when they are paid more, which raises the employer's revenue",
        "many employers compete for the same workers, which forces all wages up to the minimum",
        "workers who earn more spend more money, which increases the demand for the employer's products",
        "the government pays employers a subsidy for each additional worker who earns the minimum wage"],
    e: "Paragraph 2: \"because the employer must now pay the higher wage anyway, it no longer gains by holding wages down, and it may hire workers it previously turned away.\" Productivity and spending effects aren't mentioned." },
  { s: "rc-wages", q: "Which of the following would be an example of a condition that, according to the passage, gives employers wage-setting power?",
    o: ["A town whose only large employer is a hospital, with other employers an hour away",
        "A large city with hundreds of restaurants that all compete to hire the same cooks",
        "An industry in which job openings and wages are posted publicly online every day",
        "A market in which workers have general skills that are valued by almost every employer",
        "A region where new employers open offices frequently and compete for experienced staff"],
    e: "The passage lists long commutes to other employers, lack of information, and skills valued by few firms. A lone major employer with distant alternatives fits the first condition; the other options describe competitive markets." },
  { s: "rc-wages", q: "It can be inferred that most economists, according to the passage, would agree with which of the following?",
    o: ["Even with some monopsony power, a very high minimum wage would probably reduce employment.",
        "Minimum wages always reduce employment, no matter how small the increase is.",
        "The monopsony model describes every labor market in the world better than the textbook model does.",
        "Studies of minimum-wage increases have consistently found large losses of employment afterward.",
        "Employers never have any power to set the wages that they pay their workers."],
    e: "The last sentence: \"most agree that a minimum wage set high enough would reduce employment even where employers have some wage-setting power.\" The passage says many studies found small or no losses." }
);

SETS["rc-tardigrades"] = { title: "Passage", text: [
  "Tardigrades, microscopic animals often called water bears, are famous for surviving conditions that would kill almost any other animal. When their surroundings dry out, many species enter a state called anhydrobiosis: they curl into a compact form, lose nearly all of their body water, and slow their metabolism to an undetectable level. In this state some can survive for years and then revive within hours when water returns.",
  "For a long time, scientists assumed that tardigrades protected themselves the same way some other drought-tolerant organisms, such as brine shrimp, do: by filling their cells with a sugar called trehalose, which forms a glassy solid that holds fragile molecules in place as the water disappears. But many tardigrade species produce little or no trehalose. In the 2010s, researchers identified a family of proteins found only in tardigrades that appear to play a similar role. When cells dry out, these proteins form a glass-like matrix of their own, and when the genes for them were disabled, the animals survived drying far less often.",
  "The discovery has attracted interest beyond biology. If the proteins can protect other molecules from drying, they might one day be used to store vaccines and medicines without refrigeration, which is costly in many parts of the world. Researchers caution, however, that it is not yet clear how well the proteins will work outside tardigrade cells, or whether they are the whole story of the animals' resilience."
]};
QB.rc.push(
  { s: "rc-tardigrades", q: "The primary purpose of the passage is to",
    o: ["describe a discovery about how tardigrades survive drying and a possible use for it",
        "compare the life cycles of tardigrades and brine shrimp in dry environments",
        "argue that vaccines should no longer be stored in refrigerators in any country in the world",
        "explain why trehalose is the most important molecule for drought-tolerant organisms",
        "list the extreme conditions that tardigrades are able to survive in the wild"],
    e: "The passage explains anhydrobiosis, the new finding about tardigrade proteins (instead of trehalose), and a possible application with caveats." },
  { s: "rc-tardigrades", q: "According to the passage, which of the following was true of the tardigrades whose protein genes were disabled?",
    o: ["They survived drying far less often than tardigrades with working genes.",
        "They began to produce large amounts of trehalose to replace the proteins.",
        "They could no longer curl into a compact form when their surroundings dried.",
        "They survived drying but took several days, rather than hours, to revive.",
        "They survived drying just as often as tardigrades with working genes."],
    e: "Paragraph 2: \"when the genes for them were disabled, the animals survived drying far less often.\" Nothing is said about trehalose production or curling." },
  { s: "rc-tardigrades", q: "The author mentions brine shrimp primarily in order to",
    o: ["illustrate the mechanism that scientists had assumed tardigrades also used",
        "show that tardigrades are not the only animals that live in dry places",
        "give an example of an animal that cannot survive losing its body water",
        "suggest that proteins from brine shrimp could also be used to store vaccines and medicines",
        "explain why tardigrades are unable to produce the sugar called trehalose"],
    e: "Brine shrimp are named as organisms that protect their cells with trehalose, the method scientists long assumed tardigrades used as well." },
  { s: "rc-tardigrades", q: "The researchers' caution in the final sentence suggests that they believe",
    o: ["more research is needed before the proteins can be relied on to preserve medicines",
        "the proteins are unlikely to be the reason that tardigrades survive drying",
        "keeping vaccines in refrigerators is actually less costly than most people assume it to be",
        "trehalose would work better than the tardigrade proteins for preserving vaccines and medicines",
        "tardigrades will soon be used to produce vaccines on a large scale"],
    e: "They say it's \"not yet clear how well the proteins will work outside tardigrade cells\", so the application needs more testing. They don't deny that the proteins matter for tardigrades." }
);

SETS["rc-offices"] = { title: "Passage", text: [
  "Over the past few decades, many companies have replaced private offices and cubicles with open-plan layouts, in which employees work at desks in large shared rooms. The usual justification is collaboration: without walls, the reasoning goes, employees will run into one another more often, share ideas more freely, and solve problems together.",
  "Some recent studies have cast doubt on this reasoning. In one widely cited study, researchers used wearable sensors to record the face-to-face interactions of employees at two companies before and after the companies moved to open-plan offices. Rather than rising, face-to-face interaction fell by about two-thirds, while the number of emails and instant messages rose. The researchers suggested that when privacy disappears, employees create it in other ways: they wear headphones, avoid eye contact and move conversations to screens where colleagues can't overhear.",
  "Defenders of open offices note that such studies usually examine only a few companies over a short period, and that the benefits of an open layout may take longer to appear. They also point out that open offices are cheaper, since they fit more employees into less space, and that cost, rather than collaboration, is often the real reason for adopting them. Even so, the research suggests that companies seeking collaboration should not assume that removing walls will produce it."
]};
QB.rc.push(
  { s: "rc-offices", q: "The passage suggests that the employees in the study responded to the loss of privacy by",
    o: ["finding other ways to create privacy, such as moving conversations to email and messaging",
        "asking their companies to bring back the private offices and cubicles that they had worked in before",
        "holding more face-to-face meetings in the large shared rooms than they had held before the move",
        "working from home more often so that they could avoid the open-plan offices",
        "sharing ideas more freely with colleagues who sat at the desks nearest to them"],
    e: "The researchers suggest employees \"create [privacy] in other ways: they wear headphones, avoid eye contact and move conversations to screens.\"" },
  { s: "rc-offices", q: "The author mentions that open offices are cheaper primarily in order to",
    o: ["suggest that companies may adopt them for reasons other than collaboration",
        "argue that the savings from open offices outweigh their effect on collaboration",
        "explain why the study examined only two companies over a short period of time",
        "show that open offices increase the number of emails that employees send",
        "support the claim that face-to-face interaction rises in open-plan offices"],
    e: "The defenders point out that \"cost, rather than collaboration, is often the real reason for adopting them.\" The author doesn't weigh savings against collaboration." },
  { s: "rc-offices", q: "Which of the following best describes the organization of the passage?",
    o: ["A common rationale is stated, evidence against it is given, and objections to that evidence are weighed.",
        "A problem is described, several solutions are compared, and the best of them is recommended to companies.",
        "A study is summarized, its methods are criticized in detail, and its conclusion is rejected by the author.",
        "Two types of office layout are defined, and the history of each is traced over several decades.",
        "A new theory is proposed, tested by the author in two companies, and then revised in light of the results."],
    e: "Paragraph 1: the collaboration rationale. Paragraph 2: the sensor study against it. Paragraph 3: defenders' objections, followed by the author's measured conclusion. The author doesn't reject the study." },
  { s: "rc-offices", q: "Which of the following, if true, would most strengthen the defenders' objection described in the third paragraph?",
    o: ["A three-year study found that face-to-face interaction in open offices eventually recovered and exceeded earlier levels.",
        "A survey found that most employees in open-plan offices wear headphones for several hours each working day.",
        "A company that moved to an open-plan office saved about 30% of its annual rent in the first full year after making the move.",
        "Employees in private offices send about as many emails as employees in open-plan offices do.",
        "Wearable sensors can record face-to-face conversations accurately in both open and private offices."],
    e: "The defenders argue that benefits \"may take longer to appear\" than short studies capture. A long-term study showing interaction recovering and rising would support exactly that. Rent savings support a different point (cost)." }
);
